version: '2.2'
services:  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    container_name: elasticsearch
    environment:
      - cluster.name=Ajay-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet


#  kibana:
#    image: docker.elastic.co/kibana/kibana:6.3.2
#    container_name: kibana
#    ports: ['5601:5601']
#    networks: ['stack']
#    depends_on: ['elasticsearch']

#  logstash:
#    image: docker.elastic.co/logstash/logstash:6.3.2
#    container_name: logstash
#    networks: ['stack']
#    depends_on: ['elasticsearch']

volumes:
  esdata1:
    driver: local
networks:
  esnet:

