version: '2.2'
services:  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    container_name: elasticsearch
    environment:
      - cluster.name=Ajay-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet

  logstash:
    image: docker.elastic.co/logstash/logstash:6.3.2
    container_name: logstash
    environment:
      - http.host=0.0.0.0
      - path.config = /usr/share/logstash/pipeline
    networks: ['esnet']
    depends_on: ['elasticsearch']
    ports: ['5043:5043']
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro


  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.2
    container_name: kibana
    environment:
      - elasticsearch.url=http://elasticsearch:9200
    ports: ['5601:5601']
    networks: ['esnet']
    depends_on: ['elasticsearch']


volumes:
  esdata1:
    driver: local
networks:
  esnet:

